-- TRANSACTION
START TRANSACTION;
    DROP DATABASE code_heaven;
    SHOW DATABASES;
ROLLBACK;

DELIMITER //

CREATE PROCEDURE insert_data()

BEGIN;
DECLARE error_sql TINYINT DEFAULT false;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET error_sql = true;
START TRANSACTION;


END //